services:
  farmer-credit-app:
    image: ghcr.io/datakaveri/farmer-credit-app:v2.0
    volumes:
      - /tmp/FCcontext:/app/UIcontext
      - /tmp/FCoutput:/app/outputFolder
      - /tmp/FCinput:/app/data
